// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models
{
    public partial class Cliente
    {
        public Cliente()
        {
            Ordens = new HashSet<Ordens>();
        }

        public int IdCliente { get; set; }
        public string Nome { get; set; }
        public string Cpf { get; set; }
        public DateTime DtNascimento { get; set; }
        public bool Ativo { get; set; }

        public virtual ICollection<Ordens> Ordens { get; set; }
    }
}